name: ESLint PR review

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rpkak/ESLint-PR-review@latest
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          src: .
          eslint-format: table